"""Direct-insert pnpm error + recipe claims."""

from datetime import datetime, timezone
from hashlib import sha256

from app.schemas.claim import KnowledgeClaim
from app.schemas.enums import (
    ClaimType,
    EvidenceType,
    RiskLevel,
    TrustLevel,
)
from app.schemas.evidence import Evidence
from app.services.claim_store import get_claim_store
from app.services.embedding_service import (
    EmbeddingService,
    claim_embedding_text,
    serialize_embedding,
)
from app.services.orchestrator import CanonOrchestrator

BASE = "https://pnpm.io"

CLAIMS = [
    # ============================================================
    # pnpm-errors — 30 common errors
    # ============================================================
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_NO_PKG_MANIFEST (No package.json found)",
        "pnpm needs a package.json in the cwd (or a parent if not in workspace mode). "
        "Fix: (1) `cd` into a project directory containing package.json; "
        "(2) bootstrap: `pnpm init` creates one; "
        "(3) for workspace install at root: ensure `pnpm-workspace.yaml` exists; "
        "(4) for global add: `pnpm add -g <pkg>` doesn't need cwd package.json.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_PEER_DEP_ISSUES (peer deps unmet)",
        "A dep declared `peerDependencies` your project doesn't satisfy. By default pnpm reports but doesn't fail. "
        "Fix: (1) install the missing peer: `pnpm add <peer>@<version>`; "
        "(2) if peer is intentionally optional: set in .npmrc `auto-install-peers=true` (pnpm 8+ default); "
        "(3) for legacy hoist behavior (libraries expecting peers at top level): `pnpm install --shamefully-hoist`; "
        "(4) to silence specific peers: `pnpm.peerDependencyRules.allowedVersions` in root package.json.",
        f"{BASE}/settings",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_OUTDATED_LOCKFILE / lockfile is not up to date",
        "Lockfile doesn't match package.json (someone edited deps but didn't reinstall). "
        "Fix: (1) update locally: `pnpm install` regenerates the lockfile; "
        "(2) commit the updated `pnpm-lock.yaml`; "
        "(3) for CI: `pnpm install --frozen-lockfile` (or `--no-frozen-lockfile` to regenerate — only in dev); "
        "(4) if you can't tell what changed: `git diff pnpm-lock.yaml`.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE",
        "CI ran `pnpm install --frozen-lockfile` but lockfile doesn't match package.json. "
        "Fix: (1) commit the updated lockfile from local dev — `pnpm install` then commit `pnpm-lock.yaml`; "
        "(2) if intentional drift (e.g. range-bumping): regen locally + commit; "
        "(3) for CI bypass (NOT recommended): `pnpm install --no-frozen-lockfile` (defeats the point of frozen — only OK if you're definitely going to commit after); "
        "(4) pnpm 8.6+ enables `--frozen-lockfile` automatically when CI env var is set.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_LOCKFILE_BREAKING_CHANGE / lockfile version mismatch",
        "Lockfile was generated by a newer pnpm than the one running. "
        "Fix: (1) upgrade pnpm: `corepack prepare pnpm@latest --activate` or `pnpm self-update`; "
        "(2) pin via `packageManager` field in root package.json: `\"packageManager\": \"pnpm@9.0.0\"`; "
        "(3) for downgrade (rare): regenerate lockfile with older pnpm — `rm pnpm-lock.yaml && pnpm install`.",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_FETCH_404 / package not found",
        "Package or specific version doesn't exist on the configured registry. "
        "Fix: (1) typo check: search https://www.npmjs.com/package/<name>; "
        "(2) version range: `pnpm view <pkg> versions --json` shows what's available; "
        "(3) for private packages: ensure registry is configured + auth set: `.npmrc` with `@scope:registry=https://...` + `//<host>/:_authToken=...`; "
        "(4) for VCS deps: `git+https://github.com/...` syntax (see git fetch errors).",
        f"{BASE}/cli/add",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_FETCH_403 / auth required for private package",
        "Registry rejected the request — token missing or expired. "
        "Fix: (1) check .npmrc for token: `//<registry>/:_authToken=...`; "
        "(2) verify token: `npm whoami --registry=<url>`; "
        "(3) for GitHub Packages: token needs `read:packages` scope; "
        "(4) for AWS CodeArtifact: tokens expire (12h max) — re-auth: `aws codeartifact login --tool npm --repository <repo>`; "
        "(5) for CI: ensure secrets are passed through the workflow env.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_NO_MATCHING_VERSION / no version satisfies range",
        "Package exists but no version matches your range. "
        "Fix: (1) check available: `pnpm view <pkg> versions`; "
        "(2) loosen range: `^1.0.0` instead of `1.0.5`; "
        "(3) for prereleases: include with `--include-prereleases` or use `1.0.0-0` as lower bound; "
        "(4) for `latest` tag: `pnpm add <pkg>` (no version) picks newest stable; "
        "(5) common: package was unpublished or has only beta tags.",
        f"{BASE}/cli/add",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_BAD_TARBALL_CHECKSUM",
        "Downloaded tarball's hash doesn't match the lockfile's expected hash. Could indicate corruption, MITM, or malicious package. "
        "Fix: (1) retry: transient network corruption is most common cause; "
        "(2) clear store cache: `pnpm store prune`; "
        "(3) re-fetch fresh: `rm -rf node_modules pnpm-lock.yaml && pnpm install` (regenerates lockfile + re-verifies); "
        "(4) for suspected supply-chain: investigate before trusting — the integrity check works.",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_UNSUPPORTED_PLATFORM",
        "Package's `os`/`cpu` field doesn't include your platform. "
        "Fix: (1) check what's supported: `pnpm view <pkg> os cpu`; "
        "(2) for optional deps with platform-specific bins: usually pnpm handles automatically; "
        "(3) for forced install (NOT recommended): `--force` or set `supportedArchitectures` in .npmrc; "
        "(4) common: macOS arm64 packages missing Linux x64 wheels — pick an alternative library.",
        f"{BASE}/settings",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_UNSUPPORTED_ENGINE",
        "Package's `engines.node` requirement doesn't match your Node version. "
        "Fix: (1) check Node version: `node --version`; "
        "(2) upgrade Node: `nvm install node` or `mise use node@latest`; "
        "(3) for `--engine-strict` mode: lower or remove it in .npmrc; "
        "(4) workaround (risky): `--ignore-scripts` or `--engine-strict=false`; "
        "(5) common: newer packages require Node 18+.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_FILTER_NO_PROJECTS_MATCHED",
        "`--filter <pattern>` didn't match any workspace package. "
        "Fix: (1) list workspaces: `pnpm list -r --depth -1`; "
        "(2) filter by name: `--filter @scope/pkg` (exact) or `--filter \"./packages/*\"` (path glob); "
        "(3) filter by dir: `--filter ./packages/web` (relative path); "
        "(4) filter with deps: `--filter ...@scope/pkg` includes dependencies; "
        "(5) by changed files (since git): `--filter '[main]'`.",
        f"{BASE}/filtering",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_RECURSIVE_RUN_NO_SCRIPT",
        "`pnpm -r run <script>` found no packages with that script. "
        "Fix: (1) list scripts: search package.json across workspaces; "
        "(2) only run where script exists: `--if-present` flag — `pnpm -r --if-present run lint`; "
        "(3) check filter: combined filter may have excluded the right packages; "
        "(4) for opt-out per package: omit the script from its package.json.",
        f"{BASE}/cli/recursive",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_INVALID_NPMRC",
        "Syntax error in .npmrc. "
        "Fix: (1) ini format: `key=value` per line, no spaces around `=`; "
        "(2) comments start with `;` or `#`; "
        "(3) for tokens: don't quote: `//registry:_authToken=ghp_...` (not `\"ghp_...\"`); "
        "(4) hierarchical: pnpm reads project, user, global .npmrc — `pnpm config get <key>` shows merged value.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_BAD_WORKSPACE_VERSION / workspace:* outside workspace",
        "`workspace:*` protocol only works inside a pnpm workspace. "
        "Fix: (1) ensure `pnpm-workspace.yaml` exists at repo root with the package listed under `packages:`; "
        "(2) `workspace:*`, `workspace:^`, `workspace:~` — these are pnpm-specific; "
        "(3) on publish, pnpm rewrites them to real versions; "
        "(4) for non-workspace deps: use real semver: `^1.2.3`.",
        f"{BASE}/workspaces",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_GIT_FETCH_FAILED",
        "Git+ dependency couldn't clone. "
        "Fix: (1) verify the URL: `git ls-remote https://github.com/user/repo`; "
        "(2) for private repos: HTTPS needs PAT in URL `git+https://<token>@github.com/...` (insecure) — better, SSH with key: `git+ssh://git@github.com:user/repo.git`; "
        "(3) for a specific commit/branch: `git+https://github.com/user/repo.git#abc1234`; "
        "(4) ensure git is installed + on PATH.",
        f"{BASE}/cli/add",
    ),
    (
        "pnpm-errors", "pnpm error: ENOENT: no such file or directory, scandir 'node_modules'",
        "Trying to use something that needs node_modules before installing. "
        "Fix: (1) run `pnpm install` first; "
        "(2) for `pnpm exec <bin>`: bin must be installed; "
        "(3) for `pnpm dlx <bin>`: works without install (downloads on demand); "
        "(4) for stale node_modules after package.json changes: `pnpm install` resyncs.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-errors", "pnpm error: EBUSY: resource busy or locked",
        "Another process is using a file in node_modules (Windows file locking, antivirus, IDE indexing). "
        "Fix: (1) close VS Code / IDE that's indexing; "
        "(2) stop any running dev servers; "
        "(3) on Windows: exclude project from antivirus real-time scanning; "
        "(4) for symlink errors specifically: pnpm needs developer mode or admin on Windows for symlinks (or set `node-linker=hoisted` in .npmrc).",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-errors", "pnpm error: node-gyp / Python required",
        "Package has native bindings needing build tools. "
        "Fix: (1) install build tools: macOS `xcode-select --install`; Linux `apt install build-essential python3`; Windows `npm install -g windows-build-tools` (admin); "
        "(2) for Python 3 only (modern node-gyp): set `PYTHON=python3`; "
        "(3) skip optional natives: `pnpm install --ignore-scripts` (some packages have JS fallbacks); "
        "(4) prefer prebuilt: many packages ship binaries — `pnpm install -P` (skip dev) shrinks build surface.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-errors", "pnpm error: Cannot find module '<X>' / module not found at runtime",
        "Package is in package.json but Node can't find it. Usually pnpm's strict node_modules tripping up legacy packages. "
        "Fix: (1) pnpm uses symlinks — only declared deps are accessible (correct behavior); "
        "(2) for legacy packages expecting hoisting: `pnpm install --shamefully-hoist` (or `shamefully-hoist=true` in .npmrc); "
        "(3) for specific peer: `public-hoist-pattern[]=*<name>*` in .npmrc; "
        "(4) for monorepo: ensure dep is added to the consuming workspace's package.json (not just root).",
        f"{BASE}/symlinked-node-modules-structure",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_DIRECT_DEP_BY_RANGE_MAJOR",
        "A direct dependency would upgrade to a new major version (breaking change) and you have `prefer-stable=true` or similar guard. "
        "Fix: (1) update intentionally: `pnpm update <pkg> --latest`; "
        "(2) bump explicitly in package.json: `\"pkg\": \"^2.0.0\"` then `pnpm install`; "
        "(3) for safety: read the changelog first.",
        f"{BASE}/cli/update",
    ),
    (
        "pnpm-errors", "pnpm error: corepack version mismatch",
        "`packageManager` field in package.json doesn't match installed pnpm. "
        "Fix: (1) corepack auto-installs the right version: `corepack enable && corepack prepare pnpm@<version> --activate`; "
        "(2) for Node 16.10+: corepack ships built-in but needs `corepack enable` once; "
        "(3) update package.json: `\"packageManager\": \"pnpm@9.5.0\"`; "
        "(4) for CI: include `corepack enable` before any pnpm call.",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_STORE_NOT_DIRECTORY",
        "Configured store path isn't a directory (file in the way, or symlink broken). "
        "Fix: (1) check: `pnpm store path` shows current location; "
        "(2) clear + recreate: `rm -rf <store-path> && pnpm install` (rebuilds); "
        "(3) move store: `pnpm config set store-dir /new/path`; "
        "(4) per-project store: set `store-dir=./.pnpm-store` in project .npmrc.",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_LINK_NON_EXISTENT",
        "`pnpm link` target doesn't exist or isn't linked. "
        "Fix: (1) for global link: `cd target-pkg && pnpm link --global` then `cd consumer && pnpm link --global target-pkg`; "
        "(2) modern alternative: workspace protocol — `\"target\": \"workspace:*\"` in package.json + add to workspaces; "
        "(3) for path-based: `pnpm link ../target-pkg` (relative path).",
        f"{BASE}/cli/link",
    ),
    (
        "pnpm-errors", "pnpm error: scripts disabled / ERR_PNPM_LIFECYCLE_SCRIPTS_NOT_ENABLED",
        "Some packages need preinstall/install/postinstall scripts to build. By default pnpm 9+ runs scripts only for trusted packages. "
        "Fix: (1) approve specific packages: `pnpm approve-builds` (interactive) or list in .npmrc `onlyBuiltDependencies[]=<pkg>`; "
        "(2) allow all (risky): set `enable-pre-post-scripts=true`; "
        "(3) `pnpm install --ignore-scripts` to skip all (safest, may break native packages).",
        f"{BASE}/settings",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_HOOK_ERROR",
        "User hook in `.pnpmfile.cjs` threw. "
        "Fix: (1) check `.pnpmfile.cjs` for syntax errors: `node -e \"require('./.pnpmfile.cjs')\"`; "
        "(2) common hooks: `readPackage`, `afterAllResolved` — both must return a value; "
        "(3) remove/rename .pnpmfile.cjs to disable temporarily; "
        "(4) for stack trace: `pnpm install --loglevel=debug`.",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-errors", "pnpm error: EACCES: permission denied",
        "pnpm can't write to install location. "
        "Fix: (1) NEVER `sudo pnpm install` — fixes nothing, leaves root-owned files; "
        "(2) for `pnpm setup`: choose user-writable PNPM_HOME (default `~/.local/share/pnpm`); "
        "(3) for global install: `pnpm setup` configures PNPM_HOME + PATH; "
        "(4) for npx-style: use `pnpm dlx` (no install needed); "
        "(5) on Windows: run from admin terminal once for the setup, then normal user.",
        f"{BASE}/cli/setup",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_REGISTRIES_MISMATCH",
        "Different lockfile entries point to different registries for the same package. "
        "Fix: (1) decide: which registry is canonical?; "
        "(2) regenerate: `rm pnpm-lock.yaml && pnpm install`; "
        "(3) for scoped packages: `.npmrc` should set `@scope:registry=...` per scope; "
        "(4) for mirror: `pnpm install --registry https://mirror.example.com` once + commit lockfile.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-errors", "pnpm error: ERR_PNPM_TARBALL_INTEGRITY_FAILURE",
        "Downloaded tarball failed SRI integrity check. "
        "Fix: (1) clear store cache: `pnpm store prune`; "
        "(2) reinstall: `pnpm install` re-fetches; "
        "(3) check for proxy injection: corporate proxies sometimes rewrite tarballs; "
        "(4) if integrity in lockfile is wrong: regenerate with `rm pnpm-lock.yaml && pnpm install`.",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-errors", "pnpm error: deprecation warning for legacy npm config keys",
        "Some npm config options aren't supported (or renamed) in pnpm. "
        "Fix: (1) check pnpm settings reference: https://pnpm.io/settings; "
        "(2) common renames: `legacy-peer-deps` → `strict-peer-dependencies=false`; `package-lock` → not applicable (use `pnpm-lock.yaml`); "
        "(3) clean up legacy entries: `pnpm config delete <key>`; "
        "(4) `cat .npmrc` to inspect for old keys.",
        f"{BASE}/npmrc",
    ),

    # ============================================================
    # pnpm-recipes — 36 common workflows
    # ============================================================
    (
        "pnpm-recipes", "pnpm recipe: install pnpm itself",
        "Modern (via corepack, Node 16.10+): `corepack enable && corepack prepare pnpm@latest --activate`. "
        "Direct script: `curl -fsSL https://get.pnpm.io/install.sh | sh -` (Linux/Mac). Or: `npm install -g pnpm`. "
        "After install: `pnpm setup` configures PNPM_HOME + shell PATH. "
        "Pin per-project: add `\"packageManager\": \"pnpm@9.0.0\"` to package.json so corepack picks the right version automatically.",
        f"{BASE}/cli/setup",
    ),
    (
        "pnpm-recipes", "pnpm recipe: install deps from package.json",
        "Just: `pnpm install` (or `pnpm i`). "
        "Reproducible (CI): `pnpm install --frozen-lockfile` — fails if lockfile out of sync. "
        "Production only (skip devDeps): `pnpm install --prod` or `-P`. "
        "Offline (use cache): `pnpm install --offline`. "
        "Fresh start: `rm -rf node_modules pnpm-lock.yaml && pnpm install`.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-recipes", "pnpm recipe: add a dependency",
        "Latest: `pnpm add react`. "
        "Specific version: `pnpm add react@18.2.0`. "
        "Dev dep: `pnpm add -D vite` (or `--save-dev`). "
        "Peer dep: `pnpm add --save-peer react`. "
        "Optional: `pnpm add --save-optional fsevents`. "
        "Global (CLI tools): `pnpm add -g pnpm-deps-check`. "
        "From git: `pnpm add github:user/repo#main`.",
        f"{BASE}/cli/add",
    ),
    (
        "pnpm-recipes", "pnpm recipe: update packages",
        "Up to range: `pnpm update`. "
        "To latest (ignore range): `pnpm update --latest` (or `-L`). "
        "Specific package: `pnpm update react --latest`. "
        "Interactive (pick which): `pnpm update -i`. "
        "All workspaces: `pnpm -r update`. "
        "Match pattern: `pnpm update '@types/*' --latest`.",
        f"{BASE}/cli/update",
    ),
    (
        "pnpm-recipes", "pnpm recipe: list outdated packages",
        "`pnpm outdated` shows current vs wanted vs latest. "
        "Recursive (all workspaces): `pnpm -r outdated`. "
        "Filter: `pnpm outdated react vue`. "
        "Format JSON: `pnpm outdated --format json`. "
        "Long format with home + license: `--long`.",
        f"{BASE}/cli/outdated",
    ),
    (
        "pnpm-recipes", "pnpm recipe: why is X installed",
        "`pnpm why <pkg>` shows the dependency chain that pulled it in. "
        "Useful for debugging: 'why is left-pad here?'. "
        "All workspaces: `pnpm -r why <pkg>`. "
        "Filter by parent: `pnpm why <pkg> --filter <parent>`. "
        "Output as JSON: `--json`.",
        f"{BASE}/cli/why",
    ),
    (
        "pnpm-recipes", "pnpm recipe: run a script from package.json",
        "`pnpm <script>` (shorthand for `pnpm run <script>`). "
        "With args: `pnpm test -- --watch` (the `--` separator). "
        "All workspaces: `pnpm -r run test`. "
        "Only where script exists: `pnpm -r --if-present run lint`. "
        "Parallel: `pnpm -r --parallel run dev`. "
        "Pass-through: `pnpm exec <bin>` for binaries in node_modules/.bin.",
        f"{BASE}/cli/run",
    ),
    (
        "pnpm-recipes", "pnpm recipe: run a one-off package (dlx, npx-equivalent)",
        "`pnpm dlx <pkg> [args]` downloads + runs without installing. "
        "Example: `pnpm dlx create-vite my-app`. "
        "With version: `pnpm dlx prettier@3 --write .`. "
        "Caches in store — next run is fast. "
        "Compared to `npx`: pnpm dlx doesn't pollute node_modules, isolates per-run.",
        f"{BASE}/cli/dlx",
    ),
    (
        "pnpm-recipes", "pnpm recipe: create a workspace (monorepo)",
        "(1) Root `pnpm-workspace.yaml`: ```yaml\\npackages:\\n  - 'packages/*'\\n  - 'apps/*'\\n```. "
        "(2) Each package has its own `package.json`. "
        "(3) Cross-package deps: `\"@my-org/shared\": \"workspace:*\"` (auto-resolves to local). "
        "(4) Install everything: `pnpm install` from root. "
        "(5) Build all: `pnpm -r run build`. "
        "(6) On publish, `workspace:*` is rewritten to actual versions.",
        f"{BASE}/workspaces",
    ),
    (
        "pnpm-recipes", "pnpm recipe: filter to specific workspace packages",
        "By name: `pnpm --filter @my-org/web run dev`. "
        "By directory: `pnpm --filter './apps/*' run build`. "
        "By dependency: `pnpm --filter '...@my-org/shared' run build` (build pkg + everything depending on it). "
        "By git diff: `pnpm --filter '[main]' run test` (only changed since main). "
        "Multiple: `pnpm --filter web --filter api run dev`. "
        "Exclude: `pnpm --filter '!@my-org/docs' run build`.",
        f"{BASE}/filtering",
    ),
    (
        "pnpm-recipes", "pnpm recipe: use catalogs for shared versions",
        "Define once in `pnpm-workspace.yaml`: ```yaml\\ncatalogs:\\n  default:\\n    react: ^18.2.0\\n    typescript: ^5.0.0\\n```. "
        "Use in any workspace's package.json: `\"react\": \"catalog:\"` or `\"react\": \"catalog:default\"`. "
        "Bump once, every package picks it up. "
        "Multiple catalogs: `react18` / `react19` for monorepo migrations.",
        f"{BASE}/catalogs",
    ),
    (
        "pnpm-recipes", "pnpm recipe: migrate from npm or yarn",
        "From npm: `pnpm import` reads `package-lock.json` and generates `pnpm-lock.yaml` (preserves versions). "
        "From yarn: `pnpm import` also reads `yarn.lock`. "
        "Then: `rm package-lock.json yarn.lock node_modules && pnpm install`. "
        "Update CI: replace `npm ci`/`yarn install` with `pnpm install --frozen-lockfile`. "
        "Common gotcha: peer dep handling differs — expect some new warnings.",
        f"{BASE}/cli/import",
    ),
    (
        "pnpm-recipes", "pnpm recipe: audit dependencies for security issues",
        "Basic: `pnpm audit`. "
        "Only production: `pnpm audit --prod`. "
        "Fail CI on high severity: `pnpm audit --audit-level high` (exit 1 if issues found). "
        "Auto-fix (within ranges): `pnpm audit --fix`. "
        "JSON for tooling: `pnpm audit --json`. "
        "Ignore specific advisories: `pnpm audit --ignore-registry-errors` or use `.pnpmfile.cjs` to filter.",
        f"{BASE}/cli/audit",
    ),
    (
        "pnpm-recipes", "pnpm recipe: patch a dependency in-place",
        "(1) `pnpm patch react@18.2.0` opens a temp copy in your editor; "
        "(2) edit the files; "
        "(3) `pnpm patch-commit /path/to/temp/dir` saves a patch to `patches/`; "
        "(4) auto-applied on every `pnpm install`. "
        "Recorded in package.json under `pnpm.patchedDependencies`. "
        "For team: commit the patch file + package.json.",
        f"{BASE}/cli/patch",
    ),
    (
        "pnpm-recipes", "pnpm recipe: configure a private registry with auth",
        "In `.npmrc`: ```\\n@my-org:registry=https://npm.pkg.github.com\\n//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}\\n```. "
        "Token from env: `GITHUB_TOKEN=ghp_...` (don't commit). "
        "Test: `pnpm publish --dry-run` should resolve. "
        "For different scopes on different registries: just add multiple lines. "
        "Per-project .npmrc (in project root) overrides user-level.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-recipes", "pnpm recipe: speed up CI with persistent store",
        "Cache `~/.local/share/pnpm/store` (or `pnpm store path`) across CI runs. "
        "GitHub Actions: ```yaml\\n- uses: actions/cache@v4\\n  with:\\n    path: ~/.local/share/pnpm/store\\n    key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}\\n```. "
        "Combined with `pnpm install --frozen-lockfile`: install is near-instant on cache hit. "
        "Modern CI: `pnpm/action-setup@v3` does this automatically.",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-recipes", "pnpm recipe: deploy a single workspace package",
        "`pnpm deploy --filter @my-org/api ./out` copies the package + only its prod deps (no monorepo cruft) into `./out`. "
        "Resulting `./out` is a self-contained npm package ready for `node` runtime. "
        "Workspaces deps are inlined as real versions. "
        "Use case: Docker images, AWS Lambda packaging, single-app deployments.",
        f"{BASE}/cli/deploy",
    ),
    (
        "pnpm-recipes", "pnpm recipe: publish a package",
        "`pnpm publish` (from package directory). "
        "Workspace-aware: `pnpm publish -r` publishes all packages in workspace. "
        "Skip changed-only filter: `pnpm publish -r --filter '[main]'`. "
        "Tag: `--tag next` or `--tag beta` (default `latest`). "
        "Dry-run: `--dry-run`. "
        "Access: `--access public` (default for unscoped, required for scoped).",
        f"{BASE}/cli/publish",
    ),
    (
        "pnpm-recipes", "pnpm recipe: prune unused packages",
        "`pnpm prune` removes extraneous packages from node_modules (anything not in package.json). "
        "Production: `pnpm prune --prod` (also drops devDeps). "
        "Reduces deploy artifact size. "
        "Workspace-wide: `pnpm -r prune`.",
        f"{BASE}/cli/prune",
    ),
    (
        "pnpm-recipes", "pnpm recipe: clean the global store",
        "Free disk space: `pnpm store prune` removes packages no project references. "
        "Show usage: `pnpm store status` reports store size + content hash count. "
        "Force clean specific package: `pnpm store rm <pkg>`. "
        "Inspect store: `pnpm store path` then explore the directory tree.",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-recipes", "pnpm recipe: configure shamefully-hoist for legacy packages",
        "Some old packages assume hoisted node_modules (peer deps available implicitly). "
        "Enable: in `.npmrc` set `shamefully-hoist=true` (puts all deps at root). "
        "Better (targeted): `public-hoist-pattern[]=*eslint*` (only hoist eslint-* packages). "
        "Best (modern fix): the package should declare its peer deps properly — file an upstream issue.",
        f"{BASE}/npmrc",
    ),
    (
        "pnpm-recipes", "pnpm recipe: run a binary from node_modules",
        "`pnpm exec <bin> [args]` (equivalent of `npm exec`). "
        "Auto-installs if not present: actually, `pnpm exec` requires the bin to exist — use `pnpm dlx` for ad-hoc. "
        "Common: `pnpm exec prettier --write src/`, `pnpm exec tsc --noEmit`. "
        "From any workspace: `pnpm -F web exec vite build`.",
        f"{BASE}/cli/exec",
    ),
    (
        "pnpm-recipes", "pnpm recipe: install Node.js via pnpm env",
        "`pnpm env use --global 20` installs and uses Node 20 globally. "
        "List installed: `pnpm env list`. "
        "Per-project: pnpm respects `engines.node` in package.json. "
        "Alternative tools: nvm, fnm, volta — pnpm env is a built-in option, no extra install.",
        f"{BASE}/cli/env",
    ),
    (
        "pnpm-recipes", "pnpm recipe: write a pnpm hook (.pnpmfile.cjs)",
        "Custom logic on install. Example to enforce single version: ```js\\nmodule.exports = {\\n  hooks: {\\n    readPackage(pkg) {\\n      if (pkg.dependencies?.react && pkg.dependencies.react !== '18.3.0') {\\n        pkg.dependencies.react = '18.3.0';\\n      }\\n      return pkg;\\n    }\\n  }\\n};\\n```. "
        "Reads on every `pnpm install`. "
        "Other hooks: `afterAllResolved` (whole graph), `filterLog`. "
        "Caveat: hooks slow installs — use sparingly.",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-recipes", "pnpm recipe: configure peer dep handling",
        "Default in pnpm 8+: `auto-install-peers=true` — peers installed automatically. "
        "Strict mode (fail on unmet): `strict-peer-dependencies=true` in .npmrc. "
        "Skip warnings for specific versions: `pnpm.peerDependencyRules.allowedVersions` in root package.json: `{\"react\": \"18\"}`. "
        "Ignore missing peers entirely: `pnpm.peerDependencyRules.ignoreMissing`.",
        f"{BASE}/settings",
    ),
    (
        "pnpm-recipes", "pnpm recipe: lock pnpm version per-project (packageManager field)",
        "In root package.json: `\"packageManager\": \"pnpm@9.5.0\"`. "
        "Corepack auto-installs that exact version when anyone runs `pnpm` in the project. "
        "Enable corepack (Node 16.10+): `corepack enable` (one-time per machine). "
        "CI: include `corepack enable` step before `pnpm install`. "
        "Update version: edit package.json + commit. Team picks it up automatically.",
        f"{BASE}/configuring",
    ),
    (
        "pnpm-recipes", "pnpm recipe: use catalogs + workspace protocol together",
        "Workspace deps with `workspace:*` reference local packages — versions get inlined on publish. "
        "External deps with `catalog:` reference the catalog — versions get inlined on resolve. "
        "Combine: ```json\\n{\\n  \"dependencies\": {\\n    \"@my-org/shared\": \"workspace:*\",\\n    \"react\": \"catalog:\"\\n  }\\n}\\n```. "
        "Best for: monorepos with shared external deps that need single-source pinning.",
        f"{BASE}/catalogs",
    ),
    (
        "pnpm-recipes", "pnpm recipe: list dep licenses for compliance",
        "`pnpm licenses list` shows license for each dep. "
        "Production only: `--prod`. "
        "Workspace-wide: `pnpm -r licenses list`. "
        "JSON output: `--json` for piping to a tool. "
        "Failing on non-allowed: combine with `jq` filtering in CI.",
        f"{BASE}/cli/licenses",
    ),
    (
        "pnpm-recipes", "pnpm recipe: configure store location",
        "Global: `pnpm config set store-dir ~/.pnpm-store`. "
        "Per-project: in project .npmrc set `store-dir=./.pnpm-store`. "
        "Show current: `pnpm store path`. "
        "Why move: shared mount on CI, faster SSD, isolation per machine. "
        "Caveat: same store + cross-platform mounts don't mix (binaries differ).",
        f"{BASE}/cli/store",
    ),
    (
        "pnpm-recipes", "pnpm recipe: bisect a broken dependency",
        "When something breaks after `pnpm update`: "
        "(1) `git stash` your code; "
        "(2) note the bad lockfile state; "
        "(3) `git checkout HEAD~1 pnpm-lock.yaml && pnpm install` (or use git bisect on the lockfile); "
        "(4) once you find the offending update: `pnpm why <pkg>` traces the parent that pulled it; "
        "(5) pin the parent: `pnpm add <parent>@<known-good>`.",
        f"{BASE}/cli/why",
    ),
    (
        "pnpm-recipes", "pnpm recipe: approve native build scripts (pnpm 9+)",
        "By default pnpm 9+ blocks postinstall scripts for safety. "
        "Approve interactively: `pnpm approve-builds` (lists packages waiting). "
        "Pre-approve in .npmrc: `onlyBuiltDependencies[]=esbuild` (only listed packages can run scripts). "
        "Allow all (legacy behavior, risky): `enable-pre-post-scripts=true`. "
        "Common packages needing approval: esbuild, sharp, node-sass, prisma.",
        f"{BASE}/settings",
    ),
    (
        "pnpm-recipes", "pnpm recipe: production deployment best practices",
        "(1) Lock pnpm version: `\"packageManager\": \"pnpm@9.5.0\"` in package.json. "
        "(2) CI install: `pnpm install --frozen-lockfile --prod`. "
        "(3) Cache the store across runs (see speed-up-CI recipe). "
        "(4) For Docker: use multi-stage — build stage runs full install, runtime stage copies `pnpm deploy` output. "
        "(5) Run audit in CI: `pnpm audit --audit-level high` (fail on critical). "
        "(6) Pin scripts with `onlyBuiltDependencies` for supply-chain safety.",
        f"{BASE}/cli/install",
    ),
    (
        "pnpm-recipes", "pnpm recipe: alias a package (use one name for another)",
        "`pnpm add my-react@npm:react@18` installs react@18 but imports as `my-react`. "
        "Use case: migration (have both old and new versions), monorepo split. "
        "In package.json: `\"my-react\": \"npm:react@18.2.0\"`. "
        "Import: `import React from 'my-react'`.",
        f"{BASE}/aliases",
    ),
    (
        "pnpm-recipes", "pnpm recipe: parallel script execution in monorepo",
        "`pnpm -r --parallel run dev` runs `dev` script in ALL packages concurrently. "
        "Filtered: `pnpm --filter './apps/*' --parallel run dev`. "
        "Sequential (one at a time): drop `--parallel`. "
        "Stream order matters: `--stream` interleaves output prefixed with package name. "
        "Combine with `--filter` for selective parallel: `pnpm -F web -F api --parallel run dev`.",
        f"{BASE}/cli/recursive",
    ),
]


def main() -> None:
    store = get_claim_store()
    orchestrator = CanonOrchestrator(store)
    svc = EmbeddingService.get_default()
    now = datetime.now(timezone.utc)
    ok = 0
    failed = 0
    for i, (tool_id, subject, statement, evidence_url) in enumerate(CLAIMS):
        suffix = f"{i:03d}"
        body_for_hash = f"{subject}\n{statement}"
        evidence = Evidence(
            evidence_id=f"ev-pnpm-{suffix}",
            evidence_type=EvidenceType.OFFICIAL_DOCS,
            source_uri=evidence_url,
            excerpt=statement[:500],
            hash=f"sha256:{sha256(body_for_hash.encode()).hexdigest()}",
            captured_at=now,
            trust_level=TrustLevel.HIGH,
        )
        claim = KnowledgeClaim(
            claim_id=f"claim-pnpm-{suffix}",
            claim_type=ClaimType.CLI_COMMAND_EXISTS,
            subject=subject,
            statement=statement,
            tool_id=tool_id,
            submitted_by="pnpm-catalog",
            evidence=[evidence],
            risk_level=RiskLevel.LOW,
            created_at=now,
        )
        try:
            store.create(claim)
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ #{suffix} create: {type(exc).__name__}: {exc}")
            failed += 1
            continue
        try:
            verification = orchestrator.verify_claim(claim)
            store.save_verification_result(verification)
        except Exception as exc:  # noqa: BLE001
            print(f"  ⚠ #{suffix} verify: {type(exc).__name__}: {exc}")
        text = claim_embedding_text(subject=subject, statement=statement)
        vec = svc.embed_one(text)
        store.set_embedding(claim.claim_id, serialize_embedding(vec))
        ok += 1
        print(f"  ✓ #{suffix} [{tool_id}] {subject[:70]}")
    print(f"\nDone: {ok} created / {failed} failed")


if __name__ == "__main__":
    main()
